version: 2
updates:
  - package-ecosystem: "pip"
    directory: "/"  
    schedule:
      interval: "weekly"
    target-branch: "main" 
  - package-ecosystem: "pip"
    directory: "/"
    schedule:
      interval: "weekly"
    target-branch: "test" 

  - package-ecosystem: "cargo"
    directory: "/"  
    schedule:
      interval: "weekly"
    target-branch: "main"
  - package-ecosystem: "cargo"
    directory: "/"
    schedule:
      interval: "weekly"
    target-branch: "test"